[pytest]
testpaths = tests
pythonpath = src
log_cli = true
markers =
    id: Test case identifier
    testnet: Testnet env tests
    live: Live env tests
    demo: Demo env tests
    rest: Rest API tests
    stream: Stream API tests
    smoke: Smoke tests
    regression: Regression tests
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s